sudo: true
language: go
go:
  - 1.4
os:
  - linux
before_install:
  - bash mecab_install.sh
  - bash mecab_generate.sh
  - rm -rf cmd
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
before_script:
  - goimports -l ./ | xargs -r false
  - go vet ./...
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci
